# Generated by Django 6.0.3 on 2026-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('appraiser', 'Appraiser'), ('reviewer', 'Reviewer')], default='staff', max_length=20),
        ),
    ]
