# Generated by Django 5.2.4 on 2026-03-30 07:37

import django.db.models.deletion
from django.db import migrations, models


def migrate_departments_forward(apps, schema_editor):
    """
    Convert existing department CharField values into Department FK rows.
    At this migration step the Employee model has both the old `department`
    CharField and the new `department_fk` ForeignKey.
    """
    Employee = apps.get_model('employees', 'Employee')
    Department = apps.get_model('employees', 'Department')
    for emp in Employee.objects.all():
        dept_name = emp.department  # still the CharField at this point
        if dept_name:
            dept, _ = Department.objects.get_or_create(name=dept_name)
            emp.department_fk = dept
            emp.save(update_fields=['department_fk'])


def migrate_departments_backward(apps, schema_editor):
    pass  # no-op on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_role'),
    ]

    operations = [
        # 1. Create the Department table
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # 2. Add a temporary nullable FK column alongside the old CharField
        migrations.AddField(
            model_name='employee',
            name='department_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='employees.department',
            ),
        ),
        # 3. Populate the new FK from the old string column
        migrations.RunPython(
            migrate_departments_forward,
            migrate_departments_backward,
        ),
        # 4. Remove the old CharField
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        # 5. Rename the FK column to 'department'
        migrations.RenameField(
            model_name='employee',
            old_name='department_fk',
            new_name='department',
        ),
    ]
