# Generated by Django 5.2.4 on 2026-03-30 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reviewer_departments',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('appraiser', 'Appraiser'), ('reviewer', 'Reviewer'), ('hr', 'HR')], default='staff', max_length=20),
        ),
    ]
