# Generated by Django 5.2.4 on 2026-03-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_reviewer_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='appraiser_departments',
            field=models.ManyToManyField(blank=True, related_name='appraisers', to='employees.department'),
        ),
    ]
