# Generated by Django 6.0.3 on 2026-04-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_add_appraiser_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraiserDuty',
            fields=[
            ],
            options={
                'verbose_name': 'Appraiser Duty',
                'verbose_name_plural': 'Appraiser Duties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='ReviewerDuty',
            fields=[
            ],
            options={
                'verbose_name': 'Reviewer Duty',
                'verbose_name_plural': 'Reviewer Duties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
