# Generated by Django 6.0.3 on 2026-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeememo_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('appraiser', 'Appraiser'), ('reviewer', 'Reviewer'), ('hr', 'HR')], db_index=True, default='staff', max_length=20),
        ),
    ]
