# Generated by Django 6.0.3 on 2026-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_kra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kra',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='target',
        ),
        migrations.AddField(
            model_name='kra',
            name='appraiser_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='appraiser_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='is_visible_to_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='kra',
            name='reviewer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='reviewer_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='section',
            field=models.CharField(choices=[('section_1', 'Section 1'), ('section_2', 'Section 2'), ('section_3', 'Section 3'), ('section_4', 'Section 4'), ('section_5', 'Section 5'), ('section_6', 'Section 6')], default='section_1', max_length=30),
        ),
        migrations.AddField(
            model_name='kra',
            name='staff_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='staff_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='total_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='kra',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
