# Generated by Django 6.0.3 on 2026-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_remove_kra_actual_remove_kra_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kra',
            options={'ordering': ['section', 'sl_no']},
        ),
        migrations.RemoveField(
            model_name='kra',
            name='appraiser_comment',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='duties',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='is_visible_to_staff',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='question',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='reviewer_comment',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='staff_comment',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='staff_mark',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='total_mark',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='weight',
        ),
        migrations.AddField(
            model_name='kra',
            name='appraisee_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='kra',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kra',
            name='max_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='kra',
            name='sl_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kra',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='kra',
            name='section',
            field=models.CharField(choices=[('kra_objectives', 'KRA Objectives'), ('competencies', 'Competencies'), ('behaviour', 'Behaviour')], default='kra_objectives', max_length=30),
        ),
    ]
