# Generated by Django 6.0.3 on 2026-03-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_alter_kra_options_remove_kra_appraiser_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraiser_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='considered_for_additional_responsibilities',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='eligible_for_confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='employee_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='mgmt_hr_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='reviewer_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='strong_areas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='training_need_a',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='training_need_b',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='training_need_c',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='weak_areas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
