# Generated by Django 5.2.4 on 2026-04-20 06:03

import appraisals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_appraisal_mark_entry_access_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='frame_config',
            field=models.JSONField(blank=True, default=appraisals.models.default_frame_config),
        ),
    ]
