# Generated by Django 6.0.3 on 2026-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_kratemplate_kratemplaterow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Appraiser Reviewed', 'Appraiser Reviewed'), ('Reviewed', 'Reviewed')], default='Draft', max_length=20),
        ),
    ]
