# Generated by Django 5.2.4 on 2026-04-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_appraisal_frame_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='extra_appraiser_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
